import { JSX } from "react";
import { GeneratedRecipeResponse } from "@/services/recipeInference/generatedRecipeResponse";
import { Divider } from "@nextui-org/divider";
import { Card, CardHeader, CardBody, CardFooter } from "@nextui-org/card";

export default function RecipeDisplay(props: { recipe: GeneratedRecipeResponse }): JSX.Element {
  return (
    <Card className="flex flex-col gap-2 w-full sm:p-4 p-2">
      <CardHeader className="text-large">
        <b>{titleCaseString(props.recipe.title!)}</b>
      </CardHeader>
      <Divider/>
      <CardBody>
        <h2><b>Ingredients:</b></h2>
        <ul className="list-disc pl-4 sm:text-medium text-sm">
          {props.recipe.ingredients!.map((ingredient, index) => (
            <li key={index} id={String(index)}>{sentenceCaseText(ingredient)}</li>
          ))}
        </ul>
      </CardBody>
      <Divider/>
      <CardBody>
        <h2><b>Method:</b></h2>
        <ul className="list-disc pl-4 sm:text-medium text-sm">
          {props.recipe.method!.map((step, index) => (
            <li key={index} id={String(index)}>{sentenceCaseText(step)}</li>
          ))}
        </ul>
      </CardBody>
      <Divider/>
      <CardFooter className="text-center text-sm flex justify-center">
        This recipe was generated by AI and may contain inaccuracies or mistakes. <br/> Please verify its correctness
        before attempting to prepare it.
      </CardFooter>
    </Card>
  )
}

function titleCaseString(text: string): string {
  return text.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
}

function sentenceCaseText(text: string): string {
  return text.split(". ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(". ");
}