import { JSX, useState } from "react";

export default function Disclaimer(): JSX.Element {
  return (
    <div>
      This recipe was generated by AI. It may contain inaccuracies or mistakes.
      Please verify the correctness of the recipe before attempting to prepare it.
    </div>
  )
}