import { JSX } from "react";
import { Card, CardBody } from "@nextui-org/card";

export default function Disclaimer(): JSX.Element {
  return (
    <Card className="max-w-screen-lg">
      <CardBody className="text-center text-sm">
        This recipe was generated by AI and may contain inaccuracies or mistakes. <br/> Please verify its correctness before attempting to prepare it.
      </CardBody>
    </Card>
  )
}